#pragma once


namespace DynaPose::Systems
{
    enum class SystemStage
    {
        Origin = 0,
        // ...
        // User defined
        // ...
        ReadInGameTransforms = 1000000,
        // ...
        // User defined
        // ...
        UpdateRiggingSolvers = 2000000,
        // ...
        // User defined
        // ...
        UpdateTransformMatrices = 3000000,
        // ...
        // User defined
        // ...
        ApplyDriverNodeTransformations = 4000000,
        // ...
        // User defined
        // ...
        WriteInGameTransforms = 5000000,
        // ...
        // User defined
        // ...
    };
}